### ISSUE TITLE
loader not adding shims for Array.find / findIndex / etc

### ISSUE THREAD

**Issue by jdivock** [6to5/6to5-loader#16]
Alright, been fighting with this for a while. It looks like it's running it through the 6to5 transform just fine ad my arrow functions are being converted, but it's not adding in any of the shims pulled from core-js so my .find calls are dying. I just dumped a quick example in a repo so you can see.

https://github.com/jdivock/5to6LoaderBusted

Not sure if I missed something in the docs or what, but this should work shouldn't it?

**Comment by Couto** [comment]
That example specifically works for me.

I mean, the `document.write` output `[object Object]` to the HTML but that's to be expected.
When I switch to use `console.log` instead it outputs `{id: 123}` fine.

In my opinion, you don't need the jsx-loader when using 6to5-loader, since it already converts JSX.

On the other hand, you need to tell 6to5 to use the `core-js` shims:
```
{test: /\.jsx?$/, exclude: /node_modules/, loader: '6to5-loader?optional=coreAliasing'}
```
and you need to install core-js by issuing `npm install core-js`

**Comment by jdivock** [comment]
Actually, I missed the polyfill include that's in the 6to5 docs.

So just having this in my entry file:

```
require("6to5/polyfill");
```

Did the trick.
